#!/usr/bin/env python3
"""
GTR70E WYVERN, vectorized Monte-Carlo flight-physics core (fidelity revision, 2026-08).

Everything here operates on NumPy arrays of shape (N,) so that N independent flights
integrate in lock-step; this is what makes million-flight datasets tractable in pure
Python/NumPy. The nominal physics match `we4_flightsim.py` (the project's canonical
RK4+Barrowman engine) so datasets are consistent with the single-flight results.

MASS RECOMPUTE, 2026-08-12: bottom-up rebuild from the current CAD (`3D parts/_generator/
mass_report.json`, real geometry) + real/estimated component masses, replacing the two
disagreeing prior figures (729/627 g from an earlier reconciliation pass, 705/603 g from
the original planning-stage brief). Three real changes drove the number down:
  1. Lower BT tube: PETG-CF -> ASA-Aero (188.3 g -> 94.2 g). Hoop stress under the 140 kPa
     ejection pulse is 2.93 MPa, SF ~6-10x on ASA-Aero -- comfortable margin (see
     `3D parts/_generator/gen_rocket4.py` docstring). Motor mount/gimbal keep PC-FR (thermal
     duty), bulkhead keeps PETG-CF (direct gas-exposure part).
  2. No separate discrete UBEC line -- the onboard TPS564201 buck (PCB1) already regulates
     2S -> ~5 V; the "2S LiPo -> one 5V UBEC" in the project brief always meant that buck, not
     a second physical module. Removing the double-count drops ~5 g.
  3. Recovery consumables re-itemized (chute 58 g + Nomex 6 g + wadding 6 g = 70 g) instead of
     the older 137 g bay-lump, which CONFLICTS.md/Mathematics.md had already flagged as "very
     likely an overstatement" (sized for a sealed-bulkhead architecture that no longer applies).
  Custom PCB1 assembly mass (Ø62 mm, 2-layer FR4 + all populated parts) is a self-estimate:
  ~8.9 g bare board (volume x FR4 density 1.85 g/cm3) + ~5.2 g populated components (USB-C,
  slide switch, fuse, QFN80, 6-7 small sensor/PMIC packages, 4x JST, STEMMA-QT, H1 header,
  buck inductor, ~40 passives) = ~14 g. No bench scale weight exists yet for this or the LiPo
  pack (~27 g, comparable-product estimate) -- flag both if a real reading ever contradicts.

Canonical vehicle (F15-4, zoned ASA-Aero upper+lower body / PETG-CF fins+bulkhead / PC-FR TVC
assembly, 87 mm fins, i3 cam):
  m_lift=0.698 kg, m_dry=0.638 kg, D = 70 mm, burn 3.45 s (apogee/CG/IYY below re-run this pass).

--------------------------------------------------------------------------------------------
FIDELITY REVISION 2026-08, what changed relative to the previous core, and why
--------------------------------------------------------------------------------------------
1. INTEGRATOR. Semi-implicit Euler -> classical RK4 on the full 4-state [x, z, vx, vz].
    Euler at dt=2 ms carried a first-order local truncation error that showed up as a
    systematic apogee bias of order 1 m; RK4 removes it and lets dt be relaxed without
    losing accuracy.

2. ATMOSPHERE. Pure exponential density -> ISA troposphere with a real lapse rate:
    T(h) = T0 - L*h, P(h) = P0 * (T/T0)^(g/(R*L)), rho = P/(R*T). The exponential form is
    a first-order expansion of this and is measurably wrong once site elevation is sampled
    up to 300 m.

3. WIND. Single scalar mean wind -> power-law boundary-layer shear
    u(z) = u_ref * (z/z_ref)^alpha with alpha sampled per flight (surface-roughness
    dispersion, 0.10-0.25), plus band-limited turbulence generated by a first-order
    Dryden-form shaping filter driven by white noise, rather than the previous
    deterministic sinusoid. A fixed sinusoid is not turbulence and produced artificially
    coherent gust responses across the ensemble.

4. DRAG. Single-number Cd -> componentwise buildup evaluated per step: skin friction with
    a Reynolds-dependent turbulent flat-plate coefficient, base drag, forebody pressure
    drag, and fin profile drag, with a Prandtl-Glauert compressibility factor.

5. VEHICLE DISPERSION. Previously only atmosphere was dispersed. Now liftoff mass, CG
    station, drag coefficient, total impulse, and thrust-axis misalignment are dispersed
    per flight, which is what actually drives the apogee and landing-scatter tails.

6. RAIL PHASE. The vehicle is now genuinely constrained to the rail direction until it
    clears the rail length, and rail-exit speed is reported -- it is the gate that decides
    whether the fins have authority at release.

7. TVC LOOP. First-order servo -> second-order servo (natural frequency + damping) with a
    slew-rate limit, an explicit control transport delay ring buffer, a 500 Hz zero-order
    hold on the control update while physics integrates finer, a filtered derivative term
    matching the firmware's tau_d, and gyro noise + bias + ADC quantization on the feedback
    path. The previous model fed the controller a perfect, instantaneous, unquantized rate.
--------------------------------------------------------------------------------------------
"""
import numpy as np

# NumPy 2.0 renamed trapz -> trapezoid (and removed trapz in 2.x). Support both.
_trapz = getattr(np, "trapezoid", getattr(np, "trapz", None))

# ----------------------------------------------------------------------------- constants
G = 9.80665
D = 0.070 # body diameter [m]
RB = D / 2.0
A = np.pi * RB**2 # reference area [m^2]
LTOT = 0.74 # overall length [m]
LNOSE = 0.12
M_LIFT = 0.698 # liftoff mass [kg] (2026-08-12 recompute; ASA-Aero upper+lower/PETG-CF fins+bulkhead/PC-FR TVC, 87 mm fins)
M_DRY = 0.638 # burnout/dry mass [kg] (airframe 596.0 g + spent motor casing 42 g)
PROP = 0.060 # propellant mass [kg]
TB = 3.45 # burn time [s]
CG=0.5011 # CG from nose [m] (liftoff; 2026-08-12 item-mass recompute, we4_sim.py ITEMS)
XCP = 0.5925 # CP from nose [m] (Barrowman, 87 mm fins; unaffected by mass changes)
IYY = 0.02624 # pitch inertia [kg m^2] (2026-08-12 recompute)
PIVOT = 0.62 # gimbal pivot station from nose [m]
CN_ALPHA= 12.0 # total normal-force slope [1/rad] (nose+fins, order-of-mag)

# F15-4 ejection delay: charge fires 4 s after burnout -> recovery deploy time
DEPLOY_T = TB + 4.0 # = 7.45 s

# recovery
CHUTE_D = 0.6096 # 24 in [m]
CHUTE_A = np.pi * (CHUTE_D/2)**2 # [m^2]
CHUTE_CD = 1.5

# TVC control law (matches firmware wyvern_pid.h, 500 Hz)
KP, KI, KD = 0.10, 0.40, 0.18
TAU_D = 0.02 # derivative low-pass time constant [s] (wyvern_pid.h)
GIMBAL_LIM = np.deg2rad(8.0) # +-8 deg mechanical limit (raised from 5 for wind/weathercock authority)
TVC_ENGAGE_T = 0.5 # controller enabled at t = 0.5 s
RAIL_LEN = 1.0 # launch-rod length [m]; vehicle held straight until rail exit
CTRL_HZ = 500.0 # firmware control-loop rate [Hz]
CTRL_DT = 1.0 / CTRL_HZ

# --- actuator model (EMAX ES08MA II class, measured-typical) -------------------------------
SERVO_WN = 2 * np.pi * 6.0 # servo closed-loop natural frequency [rad/s] (~6 Hz)
SERVO_ZETA = 0.65 # servo damping ratio
SERVO_RATE = np.deg2rad(400.0) # slew-rate limit [rad/s] (0.09 s/60 deg -> ~667 deg/s no-load,
                                     # derated to 400 deg/s under gimbal load)
CTRL_DELAY_S = 0.004 # sense->actuate transport delay [s] (I2C read + loop + PWM edge)

# --- sensor model (BNO085 gyro, Game Rotation Vector mode) ---------------------------------
GYRO_NOISE_RAD_S = np.deg2rad(0.08) # rate noise density integrated to the loop bandwidth
GYRO_BIAS_RAD_S = np.deg2rad(0.15) # residual per-power-cycle bias after fusion
GYRO_LSB_RAD_S = np.deg2rad(1.0 / 16.0) # report quantization

# ISA
T0_ISA, P0_ISA, R_AIR, LAPSE = 288.15, 101325.0, 287.05, 0.0065
RHO0_ISA = P0_ISA / (R_AIR * T0_ISA)
GAMMA = 1.4
MU_AIR = 1.81e-5 # dynamic viscosity at ~15 C [Pa s]

# --- drag buildup components (Barrowman-style, see cd_buildup) -----------------------------
CD_BASE = 0.12 # base/boat-tail drag
CD_PRESS = 0.10 # forebody pressure drag (ellipsoid nose)
CD_FINS = 0.150 # 4x 72 mm fin profile drag
SWET_OVER_A = (np.pi * D * LTOT) / A # wetted-area ratio for the skin-friction term

# --- F15-4 thrust curve (digitized, renormalized to 49.6 N.s over 3.45 s) ---
_TC = np.array([0, .05, .12, .2, .3, .5, 1, 1.5, 2, 2.5, 3, 3.3, 3.45])
# F15 thrust curve CORRECTED 2026-08. The digitized shape integrated to 41.97 N.s, so the
# 49.6 N.s renormalization below scaled the whole curve by 1.1817 and pushed peak thrust to
# 29.9 N -- against Estes' published 25.3 N peak, and against the 3.26 peak T/W quoted
# throughout this repo (29.9 N gives 4.32). The sustain block (t >= 0.3 s) has been lifted by
# +2.4408 N so the curve now matches ALL THREE published values simultaneously:
# total impulse 49.6 N.s, peak 25.3 N, average 14.4 N. The renormalization is retained as a
# guard (it is now a ~1.0000 no-op) so any future re-digitization still lands on 49.6 N.s.
_FC = np.array([0, 12, 25.3, 22, 18.441, 15.441, 14.941, 14.641, 14.441, 14.241, 13.941, 9.441, 0], dtype=float)
_FC *= 49.6 / _trapz(_FC, _TC)
I_TOTAL = float(_trapz(_FC, _TC)) # 49.6 N.s


def thrust(t, impulse_scale=1.0):
    """Thrust [N] at time t (scalar or array). Zero outside the burn.

    `impulse_scale` disperses total impulse per flight (motor lot-to-lot scatter); it scales
    the whole curve, preserving shape and burn time, which is how Estes BP motors actually
    vary within a lot."""
    t = np.asarray(t, dtype=float)
    f = np.interp(t, _TC, _FC, left=0.0, right=0.0)
    return np.where((t >= 0) & (t <= TB), f, 0.0) * impulse_scale


def mass(t, m_lift=M_LIFT):
    """Instantaneous mass [kg] (linear propellant burn)."""
    t = np.clip(np.asarray(t, dtype=float), 0, TB)
    return m_lift - (PROP / TB) * t


def cd_buildup(mach, reynolds, cd_scale=1.0):
    """Componentwise Barrowman-style drag buildup (~0.54 nominal at flight Re).

    Skin friction uses the turbulent flat-plate correlation Cf = 0.074 * Re^-0.2, floored at
    the laminar-transition value so the very low-speed start of the flight cannot produce an
    unphysically large Cf. Compressibility is handled by Prandtl-Glauert below Mach 0.9 and
    an empirical transonic rise above it (WYVERN tops out near Mach 0.4, so the transonic
    branch is defensive rather than load-bearing)."""
    re = np.maximum(reynolds, 1.0e4)
    cf = np.minimum(0.074 * re ** -0.2, 0.0060)
    cd_fric = cf * SWET_OVER_A
    cd_incompressible = cd_fric + CD_BASE + CD_PRESS + CD_FINS
    m = np.clip(mach, 0.0, 0.95)
    pg = 1.0 / np.sqrt(np.maximum(1.0 - m * m, 0.05)) # Prandtl-Glauert
    transonic = 1.0 + 0.6 * np.clip(mach - 0.8, 0, None) ** 2
    return cd_incompressible * pg * transonic * cd_scale


def cd_of_mach(mach):
    """Back-compatible scalar-Mach helper (flight-Re skin friction assumed). ~0.54 nominal."""
    return cd_buildup(mach, 3.4e5)


# ----------------------------------------------------------------------------- atmosphere
def isa_state(z_geo, P0, T0):
    """ISA troposphere at geopotential altitude z_geo [m] above the sampled surface state.

    Returns (rho, a_sound, T). Replaces the previous pure-exponential density profile, which
    is only the first-order expansion of this and drifts once site elevation is dispersed."""
    z = np.maximum(z_geo, 0.0)
    T = np.maximum(T0 - LAPSE * z, 216.65)
    P = P0 * (T / T0) ** (G / (R_AIR * LAPSE))
    rho = P / (R_AIR * T)
    a = np.sqrt(GAMMA * R_AIR * T)
    return rho, a, T


def _density_profile(z, rho0, T0):
    """Back-compatible density helper (kept for callers outside this module)."""
    P0 = rho0 * R_AIR * T0
    return isa_state(z, P0, T0)[0]


def _sound_speed(z, T0):
    T = np.maximum(T0 - LAPSE * np.maximum(z, 0.0), 216.65)
    return np.sqrt(GAMMA * R_AIR * T)


def wind_at(z, u_ref, alpha, z_ref=10.0):
    """Power-law boundary-layer wind shear. u_ref is the reference speed at z_ref (10 m,
    the meteorological standard); alpha is the surface-roughness exponent (0.10 open water /
    smooth field .. 0.25 rough/suburban). Below 1 m the profile is clamped so the rail phase
    does not see a singularity."""
    return u_ref * (np.maximum(z, 1.0) / z_ref) ** alpha


# default sampling envelope (field conditions for a small F-class flight)
ENVELOPE = dict(
    wind_ms=(0.0, 15.0), # mean wind speed at the 10 m reference height
    wind_dir_deg=(0.0, 360.0), # bearing wind blows toward
    turb_pct=(0.0, 30.0), # turbulence intensity (% of mean)
    temp_C=(-15.0, 40.0), # surface temperature
    pressure_mbar=(985.0, 1030.0),
    launch_tilt_deg=(0.0, 8.0), # rod angle off vertical
    site_alt_m=(0.0, 300.0), # field elevation
    shear_alpha=(0.10, 0.25), # power-law wind-shear exponent (surface roughness)
)

# Per-flight vehicle dispersion (1-sigma unless noted). These are build/lot tolerances, not
# atmosphere, and they dominate the apogee and landing-scatter tails.
VEHICLE_DISPERSION = dict(
    mass_frac_sigma = 0.020, # +-2% liftoff mass (print density, adhesive, wiring)
    cg_sigma_m = 0.008, # +-8 mm CG station (build tolerance; cf. deepsim D sweep)
    cd_frac_sigma = 0.080, # +-8% drag coefficient (surface finish, fin alignment)
    impulse_frac_sigma = 0.030, # +-3% total impulse (Estes BP lot-to-lot)
    misalign_deg_sigma = 0.35, # thrust-axis misalignment (nozzle + gimbal null error)
)


def sample_conditions(rng, n, envelope=None, disperse_vehicle=True):
    """Draw N atmospheric/launch conditions over the envelope, plus N vehicle build dispersions.
    Returns dict of (N,) arrays."""
    e = dict(ENVELOPE)
    if envelope: e.update(envelope)
    def u(key):
        lo, hi = e[key]
        return rng.uniform(lo, hi, n) if hi > lo else np.full(n, float(lo))
    temp_C = u("temp_C"); press_mb = u("pressure_mbar")
    T0 = T0_ISA + (temp_C - 15.0) # 15 C ISA surface reference
    P0 = press_mb * 100.0
    rho0 = P0 / (R_AIR * T0)
    cond = dict(
        temp_C=temp_C, pressure_mbar=press_mb, T0=T0, P0=P0, rho0=rho0,
        wind_ms=u("wind_ms"), wind_dir_deg=u("wind_dir_deg"),
        turb_pct=u("turb_pct"), launch_tilt_deg=u("launch_tilt_deg"),
        site_alt_m=u("site_alt_m"),
        shear_alpha=u("shear_alpha") if "shear_alpha" in e else np.full(n, 0.16),
    )
    d = VEHICLE_DISPERSION
    if disperse_vehicle:
        cond["m_lift_kg"] = M_LIFT * (1.0 + rng.normal(0, d["mass_frac_sigma"], n))
        cond["cg_m"] = CG + rng.normal(0, d["cg_sigma_m"], n)
        cond["cd_scale"] = 1.0 + rng.normal(0, d["cd_frac_sigma"], n)
        cond["impulse_scale"] = 1.0 + rng.normal(0, d["impulse_frac_sigma"], n)
        cond["misalign_deg"] = rng.normal(0, d["misalign_deg_sigma"], n)
    else:
        cond["m_lift_kg"] = np.full(n, M_LIFT)
        cond["cg_m"] = np.full(n, CG)
        cond["cd_scale"] = np.ones(n)
        cond["impulse_scale"] = np.ones(n)
        cond["misalign_deg"] = np.zeros(n)
    # static margin implied by the dispersed CG (calibers)
    cond["static_margin_cal"] = (XCP - cond["cg_m"]) / D
    return cond


# ----------------------------------------------------------------------------- turbulence
class _DrydenGust:
    """First-order Dryden-form longitudinal gust filter, vectorized over N flights.

    White noise driven through a single-pole filter with the Dryden length scale gives a
    -20 dB/decade high-frequency roll-off, which is the correct qualitative spectrum for
    atmospheric turbulence at these scales. The previous model used a fixed 0.7 Hz sinusoid,
    which is coherent across the whole ensemble and therefore cannot produce a realistic
    gust-response distribution."""
    def __init__(self, rng, n, sigma, L=200.0):
        self.rng = rng; self.n = n; self.sigma = sigma; self.L = L
        self.state = np.zeros(n)

    def step(self, dt, v_air):
        # break frequency omega = V/L ; discrete first-order update with matched variance
        v = np.maximum(v_air, 1.0)
        beta = np.exp(-v * dt / self.L)
        drive = self.sigma * np.sqrt(np.maximum(1.0 - beta * beta, 1e-9))
        self.state = beta * self.state + drive * self.rng.standard_normal(self.n)
        return self.state


# ----------------------------------------------------------------------------- trajectory
def _accel(t, x, z, vx, vz, p):
    """State derivative helper: returns (vx, vz, ax, az) for the RK4 stages."""
    m = mass(t, p["m_lift"])
    Th = thrust(t, p["impulse_scale"])
    rho, a_snd, _T = isa_state(z + p["site"], p["P0"], p["T0"])
    # wind at this altitude: sheared mean + the current turbulence sample (frozen over the step)
    u_w = wind_at(z, p["wind_ref"], p["shear_alpha"]) + p["gust"]
    rvx = vx - u_w; rvz = vz
    vrel = np.sqrt(rvx * rvx + rvz * rvz) + 1e-9
    mach = vrel / a_snd
    re = rho * vrel * LTOT / MU_AIR
    q = 0.5 * rho * vrel * vrel
    Cd = cd_buildup(mach, re, p["cd_scale"])
    drag = q * Cd * A
    dfx = -drag * rvx / vrel
    dfz = -drag * rvz / vrel
    powered = Th > 0
    # thrust points along the rail while on the rail, along the velocity-ish body axis after
    ang = p["tilt"] + np.deg2rad(p["misalign_deg"]) * powered
    thx = Th * np.sin(ang) * powered
    thz = Th * np.cos(ang) * powered
    ax = (thx + dfx) / m
    az = (thz + dfz) / m - G
    return vx, vz, ax, az, mach, q, rho, vrel


def _integrate_ascent(cond, dt=0.002, trace_stride=0, rng=None):
    """
    Vectorized 2-D point-mass ascent+coast from launch to deploy (t=DEPLOY_T), RK4.
    x = downwind horizontal [m], z = altitude [m]. Wind blows toward +x.
    Returns an outcomes dict of (N,) arrays and, if trace_stride>0, a trace dict of (steps,N).
    """
    n = cond["rho0"].shape[0]
    if rng is None: rng = np.random.default_rng(0)
    p = dict(
        m_lift=cond["m_lift_kg"], impulse_scale=cond["impulse_scale"],
        cd_scale=cond["cd_scale"], misalign_deg=cond["misalign_deg"],
        P0=cond["P0"], T0=cond["T0"], site=cond["site_alt_m"],
        wind_ref=cond["wind_ms"], shear_alpha=cond["shear_alpha"],
        tilt=np.deg2rad(cond["launch_tilt_deg"]), gust=np.zeros(n),
    )
    gust = _DrydenGust(rng, n, sigma=cond["wind_ms"] * cond["turb_pct"] / 100.0)

    x = np.zeros(n); z = np.zeros(n); vx = np.zeros(n); vz = np.zeros(n)
    apo = np.zeros(n); apo_t = np.zeros(n)
    vmax = np.zeros(n); mmax = np.zeros(n); qmax = np.zeros(n); qmax_alt = np.zeros(n)
    amax = np.zeros(n)
    bo_alt = np.zeros(n); bo_v = np.zeros(n); bo_done = np.zeros(n, bool)
    rail_v = np.zeros(n); rail_done = np.zeros(n, bool); rail_t = np.zeros(n)
    cd_sum = np.zeros(n); cd_cnt = 0

    steps = int(np.ceil(DEPLOY_T / dt))
    tr = None; tr_i = 0
    if trace_stride:
        nsp = steps // trace_stride + 1
        tr = {k: np.empty((nsp, n), dtype=np.float32) for k in
              ("t", "x", "z", "vx", "vz", "accel_g", "mach", "q", "rho", "wind_local_ms")}

    t = 0.0
    for i in range(steps):
        # turbulence sample held over the step (frozen-field assumption within one dt)
        p["gust"] = gust.step(dt, np.sqrt(vx * vx + vz * vz))

        # --- RK4 on [x, z, vx, vz] ---
        k1 = _accel(t, x, z, vx, vz, p)
        k2 = _accel(t + .5*dt, x + .5*dt*k1[0], z + .5*dt*k1[1], vx + .5*dt*k1[2], vz + .5*dt*k1[3], p)
        k3 = _accel(t + .5*dt, x + .5*dt*k2[0], z + .5*dt*k2[1], vx + .5*dt*k2[2], vz + .5*dt*k2[3], p)
        k4 = _accel(t + dt, x + dt*k3[0], z + dt*k3[1], vx + dt*k3[2], vz + dt*k3[3], p)
        dx = (k1[0] + 2*k2[0] + 2*k3[0] + k4[0]) / 6.0
        dz = (k1[1] + 2*k2[1] + 2*k3[1] + k4[1]) / 6.0
        dvx = (k1[2] + 2*k2[2] + 2*k3[2] + k4[2]) / 6.0
        dvz = (k1[3] + 2*k2[3] + 2*k3[3] + k4[3]) / 6.0

        x_new = x + dt * dx; z_new = z + dt * dz
        vx_new = vx + dt * dvx; vz_new = vz + dt * dvz

        # --- rail constraint: while on the rail the vehicle cannot move off the rail line ---
        on_rail = z < RAIL_LEN
        if on_rail.any():
            spd_along = np.sqrt(vx_new * vx_new + vz_new * vz_new)
            vx_rail = spd_along * np.sin(p["tilt"]); vz_rail = spd_along * np.cos(p["tilt"])
            vx_new = np.where(on_rail, vx_rail, vx_new)
            vz_new = np.where(on_rail, vz_rail, vz_new)
            x_new = np.where(on_rail, z_new * np.tan(p["tilt"]), x_new)

        x, z, vx, vz = x_new, z_new, vx_new, vz_new
        t += dt

        # --- accumulate ---
        acc_g = np.sqrt(dvx * dvx + dvz * dvz) / G
        amax = np.maximum(amax, acc_g)
        spd = np.sqrt(vx * vx + vz * vz)
        vmax = np.maximum(vmax, spd)
        mach_i, q_i, rho_i, vrel_i = k1[4], k1[5], k1[6], k1[7]
        mmax = np.maximum(mmax, mach_i)
        newq = q_i > qmax
        qmax_alt = np.where(newq, z, qmax_alt); qmax = np.maximum(qmax, q_i)
        newapo = z > apo
        apo_t = np.where(newapo, t, apo_t); apo = np.maximum(apo, z)
        just_bo = (t >= TB) & (~bo_done)
        bo_alt = np.where(just_bo, z, bo_alt); bo_v = np.where(just_bo, spd, bo_v)
        bo_done = bo_done | (t >= TB)
        just_rail = (z >= RAIL_LEN) & (~rail_done)
        rail_v = np.where(just_rail, spd, rail_v); rail_t = np.where(just_rail, t, rail_t)
        rail_done = rail_done | (z >= RAIL_LEN)
        # effective Cd sampled over the high-q coast (the window flight telemetry can resolve)
        if TB < t < DEPLOY_T:
            re_i = rho_i * vrel_i * LTOT / MU_AIR
            cd_sum += cd_buildup(mach_i, re_i, p["cd_scale"]); cd_cnt += 1

        if trace_stride and (i % trace_stride == 0):
            tr["t"][tr_i] = t; tr["x"][tr_i] = x; tr["z"][tr_i] = z
            tr["vx"][tr_i] = vx; tr["vz"][tr_i] = vz; tr["accel_g"][tr_i] = acc_g
            tr["mach"][tr_i] = mach_i; tr["q"][tr_i] = q_i; tr["rho"][tr_i] = rho_i
            tr["wind_local_ms"][tr_i] = wind_at(z, p["wind_ref"], p["shear_alpha"]) + p["gust"]
            tr_i += 1

    out = dict(
        apogee_m=apo, apogee_t=apo_t, apogee_ft=apo * 3.28084,
        max_speed_ms=vmax, max_mach=mmax, max_q_pa=qmax, max_q_alt_m=qmax_alt,
        max_accel_g=amax,
        burnout_alt_m=bo_alt, burnout_speed_ms=bo_v,
        rail_exit_speed_ms=rail_v, rail_exit_t_s=rail_t,
        coast_cd_eff=cd_sum / max(cd_cnt, 1),
        deploy_alt_m=z.copy(), deploy_vspeed_ms=vz.copy(), deploy_x_m=x.copy(),
    )
    if trace_stride:
        for k in tr: tr[k] = tr[k][:tr_i]
    return out, tr


def _descent(cond, out):
    """Parachute descent from deploy altitude to ground, integrated against the sheared wind
    rather than the single surface value; adds landing/drift/time."""
    T0, site = cond["T0"], cond["site_alt_m"]
    P0 = cond["P0"]
    z0 = np.maximum(out["deploy_alt_m"], 0.0)
    # terminal velocity varies with density; integrate the descent in 20 altitude slices so
    # the wind-shear-weighted drift is right instead of using surface wind for the whole fall.
    nslice = 20
    t_desc = np.zeros_like(z0); drift = np.zeros_like(z0)
    for k in range(nslice):
        z_hi = z0 * (1.0 - k / nslice); z_lo = z0 * (1.0 - (k + 1) / nslice)
        z_mid = 0.5 * (z_hi + z_lo); dz = z_hi - z_lo
        rho, _a, _T = isa_state(z_mid + site, P0, T0)
        v_term = np.sqrt(2.0 * M_DRY * G / (rho * CHUTE_CD * CHUTE_A))
        dt_k = dz / np.maximum(v_term, 1e-6)
        t_desc += dt_k
        drift += wind_at(z_mid, cond["wind_ms"], cond["shear_alpha"]) * dt_k
    rho_gnd, _a, _T = isa_state(site, P0, T0)
    out["descent_rate_ms"] = np.sqrt(2.0 * M_DRY * G / (rho_gnd * CHUTE_CD * CHUTE_A))
    out["flight_time_s"] = DEPLOY_T + t_desc
    out["landing_x_m"] = out["deploy_x_m"] + drift
    out["drift_from_pad_m"] = np.abs(out["landing_x_m"])
    return out


def simulate_outcomes(n, seed=0, envelope=None, dt=0.002, disperse_vehicle=True):
    """Monte-Carlo N flights -> per-flight outcomes dict (all (N,) arrays), incl. sampled conditions."""
    rng = np.random.default_rng(seed)
    cond = sample_conditions(rng, n, envelope, disperse_vehicle=disperse_vehicle)
    out, _ = _integrate_ascent(cond, dt=dt, trace_stride=0, rng=rng)
    out = _descent(cond, out)
    out.update({k: cond[k] for k in
                ("wind_ms", "wind_dir_deg", "turb_pct", "temp_C", "pressure_mbar",
                 "launch_tilt_deg", "site_alt_m", "shear_alpha", "m_lift_kg", "cg_m",
                 "cd_scale", "impulse_scale", "misalign_deg", "static_margin_cal")})
    return out


def simulate_trace(n, seed=0, envelope=None, dt=0.002, trace_stride=10, disperse_vehicle=True):
    """N flights with full time-series. Returns (outcomes, trace, cond)."""
    rng = np.random.default_rng(seed)
    cond = sample_conditions(rng, n, envelope, disperse_vehicle=disperse_vehicle)
    out, tr = _integrate_ascent(cond, dt=dt, trace_stride=trace_stride, rng=rng)
    return out, tr, cond


# ----------------------------------------------------------------------------- TVC control
def simulate_tvc(n, seed=0, envelope=None, dt=0.001, disperse_vehicle=True):
    """
    Closed-loop pitch model under wind-gust disturbance, per flight, at the firmware's 500 Hz
    control rate with the physics integrated at `dt` (default 1 ms, i.e. 2 physics steps per
    control update -- a zero-order hold, as on the real vehicle).

    Fidelity over the previous version: second-order servo with slew-rate limit, explicit
    transport delay, filtered derivative matching wyvern_pid.h, and a noisy/biased/quantized
    gyro on the feedback path instead of perfect state access.

    Returns per-flight control metrics.
    """
    rng = np.random.default_rng(seed)
    cond = sample_conditions(rng, n, envelope, disperse_vehicle=disperse_vehicle)
    T0, P0, wind, turb = cond["T0"], cond["P0"], cond["wind_ms"], cond["turb_pct"] / 100.0
    cg = cond["cg_m"]; m_lift = cond["m_lift_kg"]; imp = cond["impulse_scale"]
    shear = cond["shear_alpha"]; misalign = np.deg2rad(cond["misalign_deg"])

    theta = np.zeros(n); omega = np.zeros(n)
    integ = np.zeros(n); d_state = np.zeros(n); prev_err = np.zeros(n)
    delta = np.zeros(n); delta_rate = np.zeros(n) # servo second-order state
    z = np.zeros(n); vz = np.full(n, 0.1)

    gyro_bias = rng.normal(0, GYRO_BIAS_RAD_S, n)
    gust = _DrydenGust(rng, n, sigma=wind * turb)

    peak_err = np.zeros(n); sat_steps = np.zeros(n); nsteps = 0
    sum_d2 = np.zeros(n); sum_e2 = np.zeros(n); settle_t = np.full(n, np.nan)
    peak_rate = np.zeros(n); ctrl_updates = 0

    arm = PIVOT - cg
    I_MAX = GIMBAL_LIM / KI # anti-windup: cap integral's authority at the gimbal limit
    ZETA = 0.15 # aero pitch-damping ratio (light)

    # transport-delay ring buffer on the commanded gimbal angle
    ndelay = max(int(round(CTRL_DELAY_S / dt)), 1)
    delay_buf = np.zeros((ndelay, n))
    di = 0

    cmd_held = np.zeros(n) # zero-order-held control output
    t = 0.0
    steps = int(np.ceil((TB + 1.0) / dt))
    ctrl_every = max(int(round(CTRL_DT / dt)), 1)

    for i in range(steps):
        Th = thrust(t, imp); m = mass(t, m_lift)
        vz = vz + np.where(Th > 0, Th / m - G, np.where(z > 0, -G, 0.0)) * dt
        vz = np.maximum(vz, 0.1)
        z = z + vz * dt
        rho, _a, _T = isa_state(z, P0, T0)
        q = 0.5 * rho * vz * vz
        u_w = wind_at(z, wind, shear) + gust.step(dt, vz)
        alpha_w = np.arctan2(u_w, np.maximum(vz, 1.0)) # wind-induced AoA
        k_aero = q * A * CN_ALPHA * (XCP - cg) # restoring stiffness (>0)
        c_aero = 2.0 * ZETA * np.sqrt(np.maximum(k_aero, 0.0) * IYY) # damping
        on_rail = z < RAIL_LEN

        # ---- controller: runs only every ctrl_every physics steps (500 Hz ZOH) ----
        if i % ctrl_every == 0:
            # noisy, biased, quantized rate feedback (BNO085 GRV report)
            omega_meas = omega + gyro_bias + rng.normal(0, GYRO_NOISE_RAD_S, n)
            omega_meas = np.round(omega_meas / GYRO_LSB_RAD_S) * GYRO_LSB_RAD_S
            theta_meas = theta + rng.normal(0, np.deg2rad(0.05), n)
            err = theta_meas
            integ = np.clip(integ + err * CTRL_DT, -I_MAX, I_MAX)
            # filtered derivative, matching wyvern_pid.h's tau_d low-pass on de/dt
            raw_d = (err - prev_err) / CTRL_DT
            alpha_f = CTRL_DT / (TAU_D + CTRL_DT)
            d_state = d_state + alpha_f * (raw_d - d_state)
            prev_err = err
            # firmware uses measured rate for the D path when available; blend as flown
            delta_cmd = KP * err + KI * integ + KD * (0.5 * d_state + 0.5 * omega_meas)
            engaged = (t >= TVC_ENGAGE_T) & (Th > 1.0) & (~on_rail)
            sat_steps += ((np.abs(delta_cmd) >= GIMBAL_LIM) & engaged)
            cmd_held = np.clip(delta_cmd, -GIMBAL_LIM, GIMBAL_LIM) * engaged
            ctrl_updates += 1

        # ---- transport delay ----
        delay_buf[di] = cmd_held
        di = (di + 1) % ndelay
        cmd_delayed = delay_buf[di]

        # ---- second-order servo with slew-rate limit ----
        acc = SERVO_WN**2 * (cmd_delayed - delta) - 2 * SERVO_ZETA * SERVO_WN * delta_rate
        delta_rate = np.clip(delta_rate + acc * dt, -SERVO_RATE, SERVO_RATE)
        delta = np.clip(delta + delta_rate * dt, -GIMBAL_LIM, GIMBAL_LIM)
        peak_rate = np.maximum(peak_rate, np.abs(delta_rate))

        # ---- plant ----
        M_tvc = -Th * np.sin(delta) * arm
        M_mis = Th * np.sin(misalign) * arm * (Th > 0) # thrust-axis misalignment torque
        ang_acc = (k_aero * (alpha_w - theta) - c_aero * omega + M_tvc + M_mis) / IYY
        omega = np.where(on_rail, 0.0, omega + ang_acc * dt)
        theta = np.where(on_rail, 0.0, theta + omega * dt)

        adeg = np.abs(np.rad2deg(theta))
        peak_err = np.maximum(peak_err, adeg)
        sum_d2 += np.rad2deg(delta) ** 2
        sum_e2 += adeg ** 2
        newly = np.isnan(settle_t) & (adeg < 1.0) & (t > TVC_ENGAGE_T)
        settle_t = np.where(newly, t, settle_t)
        t += dt; nsteps += 1

    return dict(
        peak_pitch_err_deg=peak_err,
        rms_pitch_err_deg=np.sqrt(sum_e2 / nsteps),
        rms_gimbal_deg=np.sqrt(sum_d2 / nsteps),
        gimbal_saturation_pct=100.0 * sat_steps / max(ctrl_updates, 1),
        peak_gimbal_rate_dps=np.rad2deg(peak_rate),
        settle_time_s=np.nan_to_num(settle_t, nan=-1.0),
        wind_ms=cond["wind_ms"], turb_pct=cond["turb_pct"],
        temp_C=cond["temp_C"], pressure_mbar=cond["pressure_mbar"],
        launch_tilt_deg=cond["launch_tilt_deg"], shear_alpha=cond["shear_alpha"],
        cg_m=cond["cg_m"], static_margin_cal=cond["static_margin_cal"],
        misalign_deg=cond["misalign_deg"],
    )


def simulate_tvc_trace(kp=KP, ki=KI, kd=KD, gimbal_deg=8.0, wind=8.0, turb=15.0,
                       disturbance="Wind gust", temp_C=15.0, pressure_mbar=1013.25, dt=0.001,
                       seed=0):
    """
    Single-flight closed-loop pitch response for interactive PID tuning. Same plant and same
    actuator/sensor models as simulate_tvc(), but scalar, with user gains + gimbal limit,
    returning full time-series and tuning metrics. Two disturbances:
      "Wind gust" : aerodynamic AoA forcing from the (turbulent) crosswind.
      "Initial tip 10 deg": released 10 deg off vertical in calm air (classic step recovery).
    """
    rng = np.random.default_rng(seed)
    T0 = T0_ISA + (temp_C - 15.0); P0 = pressure_mbar * 100.0
    lim = np.deg2rad(gimbal_deg)
    I_MAX = lim / ki if ki > 1e-9 else 1e6
    ZETA = 0.15; arm = PIVOT - CG
    step_mode = disturbance.startswith("Initial")
    theta = np.deg2rad(10.0) if step_mode else 0.0
    omega = 0.0; integ = 0.0; d_state = 0.0; prev_err = 0.0
    delta = 0.0; delta_rate = 0.0
    z = 0.0; vz = 0.1; t = 0.0
    gyro_bias = rng.normal(0, GYRO_BIAS_RAD_S)
    gust = _DrydenGust(rng, 1, sigma=np.array([wind * turb / 100.0]))
    steps = int(np.ceil((TB + 1.5) / dt))
    ctrl_every = max(int(round(CTRL_DT / dt)), 1)
    ndelay = max(int(round(CTRL_DELAY_S / dt)), 1)
    delay_buf = np.zeros(ndelay); di = 0; cmd_held = 0.0
    T = np.empty(steps); TH = np.empty(steps); DE = np.empty(steps); CM = np.empty(steps)
    for i in range(steps):
        Th = float(thrust(t)); m = float(mass(t))
        vz += (Th / m - G) * dt if Th > 0 else (-G * dt if z > 0 else 0.0)
        vz = max(vz, 0.1); z += vz * dt
        rho, _a, _T = isa_state(z, P0, T0); q = 0.5 * rho * vz * vz
        if step_mode:
            alpha_w = 0.0
        else:
            u_w = wind_at(z, wind, 0.16) + float(gust.step(dt, np.array([vz]))[0])
            alpha_w = np.arctan2(u_w, max(vz, 1.0))
        k_aero = q * A * CN_ALPHA * (XCP - CG)
        c_aero = 2.0 * ZETA * np.sqrt(max(k_aero, 0.0) * IYY)
        on_rail = z < RAIL_LEN
        if i % ctrl_every == 0:
            omega_meas = omega + gyro_bias + rng.normal(0, GYRO_NOISE_RAD_S)
            omega_meas = round(omega_meas / GYRO_LSB_RAD_S) * GYRO_LSB_RAD_S
            err = theta + rng.normal(0, np.deg2rad(0.05))
            integ = float(np.clip(integ + err * CTRL_DT, -I_MAX, I_MAX))
            raw_d = (err - prev_err) / CTRL_DT
            alpha_f = CTRL_DT / (TAU_D + CTRL_DT)
            d_state += alpha_f * (raw_d - d_state)
            prev_err = err
            delta_cmd = kp * err + ki * integ + kd * (0.5 * d_state + 0.5 * omega_meas)
            engaged = (t >= TVC_ENGAGE_T) and (Th > 1.0) and (not on_rail)
            cmd_held = float(np.clip(delta_cmd, -lim, lim)) if engaged else 0.0
        delay_buf[di] = cmd_held; di = (di + 1) % ndelay
        cmd_delayed = delay_buf[di]
        acc = SERVO_WN**2 * (cmd_delayed - delta) - 2 * SERVO_ZETA * SERVO_WN * delta_rate
        delta_rate = float(np.clip(delta_rate + acc * dt, -SERVO_RATE, SERVO_RATE))
        delta = float(np.clip(delta + delta_rate * dt, -lim, lim))
        M_tvc = -Th * np.sin(delta) * arm
        ang_acc = (k_aero * (alpha_w - theta) - c_aero * omega + M_tvc) / IYY
        if on_rail:
            omega = 0.0
        else:
            omega += ang_acc * dt; theta += omega * dt
        T[i] = t; TH[i] = np.rad2deg(theta); DE[i] = np.rad2deg(delta)
        CM[i] = np.rad2deg(cmd_held)
        t += dt
    m_eng = T >= TVC_ENGAGE_T
    adeg = np.abs(TH)
    peak = float(adeg[m_eng].max()) if m_eng.any() else 0.0
    ss = float(np.mean(adeg[T >= T[-1] - 0.3]))
    over = np.where(m_eng & (adeg > 1.0))[0]
    settle = float(T[over[-1]]) if over.size else TVC_ENGAGE_T
    sat = 100.0 * float(np.mean(np.abs(CM[m_eng]) >= gimbal_deg - 1e-6)) if m_eng.any() else 0.0
    rms = float(np.sqrt(np.mean(DE[m_eng] ** 2))) if m_eng.any() else 0.0
    metrics = dict(peak_pitch_deg=peak, steady_err_deg=ss, settle_time_s=settle,
                   rms_gimbal_deg=rms, gimbal_saturation_pct=sat)
    return dict(t=T, theta_deg=TH, delta_deg=DE, cmd_deg=CM, metrics=metrics)


if __name__ == "__main__":
    # quick nominal sanity check (zero-wind, ISA, no vehicle dispersion) against we4_flightsim
    nominal = dict(wind_ms=(0, 0), wind_dir_deg=(0, 0), turb_pct=(0, 0),
                   temp_C=(15, 15), pressure_mbar=(1013.25, 1013.25),
                   launch_tilt_deg=(0, 0), site_alt_m=(0, 0), shear_alpha=(0.16, 0.16))
    o = simulate_outcomes(1, seed=1, envelope=nominal, dt=0.001, disperse_vehicle=False)
    print(f"nominal apogee = {o['apogee_m'][0]:.1f} m / {o['apogee_ft'][0]:.0f} ft "
          f"@ t={o['apogee_t'][0]:.2f} s ; max Mach {o['max_mach'][0]:.2f} ; "
          f"rail exit {o['rail_exit_speed_ms'][0]:.1f} m/s ; coast Cd {o['coast_cd_eff'][0]:.3f} ; "
          f"descent {o['descent_rate_ms'][0]:.1f} m/s ; flight {o['flight_time_s'][0]:.1f} s")
